---
- name: download chruby and ruby-install
  shell: yay -S --noconfirm chruby ruby-install

- name: install latest ruby
  become: true
  shell: ruby-install --system ruby

- name: install bundler
  become: true
  shell: gem install bundler

