---
- name: Ensure NFS is installed
  package: "name=nfs-common state=installed"

- name: Get current AZ from AWS
  uri:
    url: http://169.254.169.254/latest/meta-data/placement/availability-zone
    return_content: yes
  register: aws_current_az

- name: Ensure EFS directory exists
  file:
    path: "/efs"
    state: directory
    group: grant
    mode: 0775

- name: Ensure EFS volume is mounted
  mount:
    name: "/efs"
    src: "{{ aws_current_az.content }}.{{ efs_file_system_id }}.efs.{{ aws_region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1
    state: mounted

- name: Symlink Maildir directory
  become: true
  become_user: grant
  file:
    src: /efs/Maildir
    dest: /home/grant/Maildir
    state: link
