---
- name: upload main.cf
  become: true
  copy:
    src: postfix/main.cf
    dest: /etc/postfix/

- name: upload master.cf
  become: true
  copy:
    src: postfix/master.cf
    dest: /etc/postfix/

- name: upload virtual
  become: true
  copy:
    src: postfix/virtual
    dest: /etc/postfix/

- name: create virtual db
  become: true
  shell: postmap /etc/postfix/virtual

- name: remove ssl dir
  become: true
  file:
    name: /etc/ssl
    state: absent

- name: symlink ssl dir from /efs
  become: true
  file:
    src: /efs/ssl
    dest: /etc/ssl
    state: link

- name: create openssl dh512
  tags: mail-master
  become: true
  shell: openssl dhparam -out /etc/ssl/dh512.pem 512

- name: create openssl dh2048
  tags: mail-master
  become: true
  shell: openssl dhparam -out /etc/ssl/dh1024.pem 2048

- name: reload postfix
  become: true
  shell: systemctl restart postfix
