---
- name: Setup base packages
  become: true
  pacman: name={{ item }}
  with_items:
    - xorg-xinit
    - i3-gaps
      #- xbacklight // try acpilight?
    - xclip
    - syncthing
    - pasystray
    - imwheel
    - v4l2ucp
    - i3lock
    - xautolock
    - feh
    - numlockx
    - rofi
    - ttf-font-awesome
    - ttf-inconsolata
    - dunst
      #- redshift-gtk
    - spectacle
