---
- name: Setup base packages
  become: true
  pacman:
    name:
      - xorg
      - xf86-video-intel
      - vulkan-intel
      - xorg-xinit
      - i3-gaps
      - xorg-xbacklight
      - xclip
      - pasystray
      - imwheel
      - i3lock
      - xautolock
      - feh
      - numlockx
      - rofi
      - dunst
      - networkmanager
      - network-manager-applet
      - ttf-dejavu
      - ttf-ubuntu-font-family
      - ttf-font-awesome
      - ttf-hack
      - ttf-inconsolata
      - ttf-roboto-mono
      - powerline
      - awesome-terminal-fonts
      - noto-fonts-emoji
      - tlp
      - powertop
      - pulseaudio
      - alsa-utils
      - cpupower
      - playerctl
      - lightdm
      - xscreensaver
      - kitty
      - maim
      - gnome-keyring

- name: add gui packages from aur
  shell: yay -S --noconfirm picom networkmanager-openvpn nmap remmina steam google-chrome i3-gnome

- name: add a browser
  shell: yay -S google-chrome --noconfirm

- name: enable networkmanager
  become: true
  shell: systemctl enable NetworkManager.service

# - name: start networkmanager
#   become: true
#   shell: systemctl start NetworkManager.service
