---
- name: Setup base packages
  become: true
  pacman: name={{ item }}
  with_items:
    - xorg
    - xf86-video-intel
    - xorg-xinit
    - i3-gaps
    - xorg-xbacklight
    - xclip
    - syncthing
    - pasystray
    - imwheel
    - i3lock
    - xautolock
    - feh
    - numlockx
    - rofi
    - ttf-inconsolata
    - dunst
    - plasma5-applets-redshift-control
    - spectacle
    - networkmanager
    - network-manager-applet
    - ttf-dejavu
    - ttf-ubuntu-font-family
    - ttf-font-awesome
    - awesome-terminal-fonts
    - noto-fonts-emoji
    - tlp
    - powerline
    - pulseaudio
    - alsa-utils
    - cpupower
    - playerctl
    - deepin-screenshot
      yay -S deepin-screenshot brightnessctl cpupower docker docker-compose gdm jq kubectl-bin kubernetes-helm-git minikube-bin networkmanager-openvpn networkmanager-strongswan nmap remmina spotify slack-desktop steam xscreensaver zoom

- name: add fzf
  shell: yay -S --noconfirm fzf polybar ttf-weather-icons

- name: enable networkmanager
  become: true
  shell: systemctl enable NetworkManager.service

- name: start networkmanager
  become: true
  shell: systemctl start NetworkManager.service
