---
- name: Setup base packages
  become: true
  pacman: name={{ item }}
  with_items:
    - xorg-xinit
    - i3-gaps
      #- xbacklight // try acpilight?
    - xclip
    - syncthing
    - pasystray
    - imwheel
    - v4l2ucp
    - i3lock
    - xautolock
    - feh
    - numlockx
    - rofi
    - ttf-font-awesome
    - ttf-inconsolata
    - dunst
    - plasma5-applets-redshift-control
    - spectacle
    - networkmanager
    - network-manager-applet
    - ttf-dejavu
    - ttf-ubuntu-font-family
    - tlp
    - powerline


- name: add fzf
  shell: yay -S --noconfirm polybar

