---
- name: Setup base packages
  become: true
  pacman: name={{ item }}
  with_items:
    - xorg
    - xf86-video-intel
    - xorg-xinit
    - i3-gaps
    - xorg-xbacklight
    - xclip
    - syncthing
    - pasystray
    - imwheel
    - v4l2ucp
    - i3lock
    - xautolock
    - feh
    - numlockx
    - rofi
    - ttf-font-awesome
    - ttf-inconsolata
    - dunst
    - plasma5-applets-redshift-control
    - spectacle
    - networkmanager
    - network-manager-applet
    - ttf-dejavu
    - ttf-ubuntu-font-family
    - tlp
    - powerline
    - pulseaudio
    - alsa-utils
    - awesome-terminal-fonts
    - cpupowe

- name: add fzf
  shell: yay -S --noconfirm fzf polybar ttf-weather-icons

- name: enable networkmanager
  become: true
  shell: systemctl enable NetworkManager.service

- name: start networkmanager
  become: true
  shell: systemctl start NetworkManager.service
