---
- name: create unifi directories
  file:
    path: /home/grant/unifi/data
    state: directory

- name: create unifi directories
  file:
    path: /home/grant/unifi/log
    state: directory

- name: create systemd file
  copy:
    src: unifi.service
    dest: /home/grant/.config/systemd/user/

- name: enable unifi service
  shell: systemctl --user enable unifi.service

- name: start unifi service
  shell: systemctl --user start unifi.service
