---
- name: create unifi directories
  file:
    path: /home/grant/unifi/data
    state: directory

- name: create unifi directories
  file:
    path: /home/grant/unifi/log
    state: directory

- name: create systemd file
  become: true
  copy:
    src: unifi.service
    dest: /etc/systemd/system/unifi.service

- name: enable unifi service
  shell: systemctl enable unifi.service

- name: start unifi service
  shell: systemctl start unifi.service
