---
- include: libs.yml
- include: i3-gaps.yml
- include: polybar.yml

- name: remove lightdm.conf file to not autologin with unity
  become: true
  file:
    name: /etc/lightdm/lightdm.conf
    state: absent
