---
- name: clone my dotfiles
  git:
    repo: 'https://github.com/gammons/dotfiles-local.git'
    dest: ~/dotfiles

- name: Create SSH directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0600'

- name: Get grant public key
  become: true
  get_url:
    owner: grant
    group: grant
    url: https://github.com/gammons.keys
    dest: /home/grant/.ssh/id_rsa.pub
    mode: 0600

