---
- name: create systemd file
  become: true
  copy:
    src: unifi.service
    dest: /etc/systemd/system/

- name: enable unifi service
  shell: systemctl enable unifi.service

- name: start unifi service
  shell: systemctl start unifi.service
