---
- name: create systemd file
  become: true
  copy:
    src: pihole.service
    dest: /etc/systemd/system/pihole.service

- name: enable pihole service
  shell: systemctl enable pihole.service

- name: start pihole service
  shell: systemctl start pihole.service
