---
- name: get the install script
  get_url:
    url: https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh
    dest: docker_run.sh
    mode: 0744

- name: run the install script
  shell: ./docker_run.sh
