---
- name: Setup base packages
  become: true
  apt: pkg={{ item }}
  with_items:
    - postgresql
    - libpq-dev
    - libsqlite3-dev

- name: Setup Golang
  become: true
  apt:
    name: golang-go
    state: present

- name: install tmuxinator
  shell: gem install tmuxinator

- name: install yarn key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add latest node repo
  become: true
  shell: curl -sL https://deb.nodesource.com/setup_6.x

- name: install nodejs
  become: true
  apt:
    name: nodejs
    state: present

- name: add yarn repo
  become: true
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: install yarn
  become: true
  apt:
    name: yarn
    state: present
