---
- name: Sync pacman
  become: true
  shell: pacman -Syu --noconfirm

- name: Setup base packages
  become: true
  pacman: name={{ item }}
  with_items:
    - base-devel
    - vim
    - git
    - ntp
    - tmux
    - htop
    - the_silver_searcher
    - tig
    - zsh
    - ntp
    - curl
    - aws-cli
    - snapper
    - btrbk

- name: Install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Change shell to zsh
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh

- name: clone thoughtbot's dotfiles
  git:
    repo: https://github.com/gammons/dotfiles.git
    dest: ~/dotfiles

- name: clone my dotfiles
  git:
    repo: 'https://github.com/gammons/dotfiles-local.git'
    dest: ~/dotfiles-local

- name: add RCM
  shell: yay -S --noconfirm rcm

- name: run rcup for first time
  shell: env RCRC=$HOME/dotfiles/rcrc rcup
  async: 30
  poll: 0

- name: install base16-shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.config/base16-shell

- name: add fzf
  shell: yay -S --noconfirm fzf

# - name: Get grant public key
#   become: true
#   get_url:
#     owner: grant
#     group: grant
#     url: https://github.com/gammons.keys
#     dest: /home/grant/.ssh/id_rsa.pub
#     mode: 0600
