---
- name: Sync pacman
  become: true
  shell: pacman -Syu --noconfirm

- name: Setup base packages
  become: true
  pacman:
    name:
      - base-devel
      - zsh
      - neovim
      - git
      - ntp
      - tmux
      - htop
      - the_silver_searcher
      - tig
      - zsh
      - ntp
      - curl
      - aws-cli
      - throttled
      - fd
      - go
      - starship

- name: Install vim-plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Change shell to zsh
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh

- name: clone yay
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /tmp/yay

- name: install yay
  shell: cd /tmp/yay && makepkg -si --noconfirm

- name: add RCM
  shell: yay -S --noconfirm rcm

- name: add exa
  shell: yay -S exa --noconfirm

- name: run rcup for first time
  shell: env RCRC=$HOME/dotfiles/rcrc rcup
  async: 30
  poll: 0

- name: install base16-shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.config/base16-shell

- name: add fzf
  shell: yay -S --noconfirm fzf


- name: python stuff
  shell: yay -S --noconfirm python3 python-pip

- name: ensure pynvim stuff is installed
  shell: pip3 install --user pynvim
