---
- name: add the syncthing apt key
  become: true
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: add the syncthing apt repo
  become: true
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: install syncthing
  become: true
  apt:
    name: syncthing
    state: present

- name: install the syncthing systemd service
  get_url:
    url: https://raw.githubusercontent.com/syncthing/syncthing/master/etc/linux-systemd/user/syncthing.service
    dest: ~/syncthing.service

- name: register the syncthing systemd service
  shell: systemctl --user enable syncthing.service

- name: start the syncthing service
  shell: systemctl --user start syncthing.service
