---
- name: Setup dev packages
  become: true
  pacman: name={{ item }}
  with_items:
    - go
    - docker
    - docker-compose
    - docker-machine-driver-kvm2
    - jq

- name: download chruby and ruby-install
  shell: yay -S --noconfirm chruby ruby-install

- name: install latest ruby
  become: true
  shell: ruby-install --system ruby

- name: install bundler
  become: true
  shell: gem install bundler

- name: increase number of fs inotify watches
  become: true
  shell: echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p

# needed for elasticsearch in docker
- name: increase number of vm.max_map_count
  become: true
  shell: echo vm.max_map_count=262144 | tee -a /etc/sysctl.conf && sysctl -p
