---
- name: Setup dev packages
  become: true
  pacman:
    name:
      - go
      - docker
      - docker-compose
      - jq

- name: increase number of fs inotify watches
  become: true
  shell: echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf

# needed for elasticsearch in docker
- name: increase number of vm.max_map_count
  become: true
  shell: echo vm.max_map_count=262144 | tee -a /etc/sysctl.conf

- name: bounce sysctl
  become: true
  shell: sysctl -p
  ignore_errors: yes

- name: add kubernetes items
  shell: yay -S --noconfirm kubectl-bin minikube-bin kubectl-bin kubernetes-helm

- name: add stripe cli
  shell: yay -S --noconfirm stripe-cli

- name: add asdf vm
  shell: yay -S --noconfirm asdf-vm

- name: add mariadb
  shell: yay -S --noconfirm mariadb

- name: add yarn
  shell: yay -S --noconfirm yarn
