---
- name: provision ec2 instance
  ec2:
    instance_type: t2.nano
    image: ami-0e4365d20993ad90c # ubuntu server 18.04 with python
    wait: true
    group_id: sg-0a05431759a0a2584 # mail server security group
    key_name: id_rsa
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: associate the eip with the instance
  ec2_eip:
    device_id: "{{ item.id }}"
    ip: 18.218.22.123
  with_items: "{{ ec2.instances }}"
